@host = http://10.10.2.158:5000
# Login
# @name tokenAPI
POST {{host}}/authentication/authenticate HTTP/1.1
Content-Type: application/json

{
    "acc": "a5374",
    "pwd": "121212"
}
###

@authToken = {{tokenAPI.response.body.token}}

GET {{host}}/skyeye/defect/image
?MachineName=20&ReelNo=T4060412&RangeStart=0&ReelEnd=1000
Content-Type: application/json
Authorization: Bearer {{authToken}}
